"""
Write the visual-review manifest.

Says honestly what each Python/Java pair is, and what it is not. The two sides
are produced by two independent programs from two independent seeds, so gold
totals, wind direction, storm state, escape timers and spawn positions differ
between them by design. That is expected and is **not** evidence of a gameplay
parity failure — gameplay parity is the job of the 771 fixtures and the unit
suite, not of a screenshot.

    python java-port/tools/visual/manifest.py OUT_DIR
"""

import os
import subprocess
import sys

SCENES = [
    ("mixed-wave", "a busy ordinary wave: what most of the game looks like"),
    ("all-enemies", "one of every ordinary unit, spread along the field"),
    ("all-bosses", "three bosses placed; only two get bars, as the source caps at two"),
    ("all-towers", "every tower type bought twice, walls reinforced three times"),
    ("armour", "three Siege Rams: plated, one plate off, fully stripped"),
    ("regalia", "Troll King and Lich Lord with crown and staff detached"),
    ("dragon-breath", "stepped until the Dragon's own breath timer fired"),
    ("lich-ward", "Lich Lord with his summoned skeletons"),
    ("fire-zone", "Meteor cast, so the ground is burning"),
    ("tornado", "Tornado cast, then stepped 90 frames so it has caught mobs"),
    ("storm", "weather rolled until a thunderstorm broke"),
    ("endless-late", "wave 40, so every mob carries the Voidtouched tier tint"),
]


def git_rev():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:                                   # noqa: BLE001
        return "(unknown)"


def main():
    #  Run this straight after the captures, never later: the hash below is
    #  HEAD at THIS moment, and a manifest written a commit after the images it
    #  describes is a manifest that lies about them.  That happened once.
    out = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(out, exist_ok=True)
    rev = git_rev()

    lines = [
        "# Visual review manifest",
        "",
        "Generated by `tools/visual/manifest.py`.",
        "",
        "| | |",
        "|---|---|",
        "| Java build | `%s` (HEAD when this manifest was written) |" % rev,
        "| Python source | `main.py`, `sprites.py`, `castle.py`, `enemies.py` "
        "— imported unmodified |",
        "| Java capture | `--scenario NAME --mode endless --frames 20`, desktop "
        "frame 1280x720 |",
        "| Python capture | `tools/visual/python_reference.py`, same scene names, "
        "drawn once after the scene is built |",
        "| Shake | forced to zero on the Python side so the reference is stable; "
        "it is a visual offset only |",
        "",
        "## Every pair is REPRESENTATIVE-STATE, not exact-state",
        "",
        "The two sides run different programs from different seeds. Gold totals, "
        "wind direction, storm state, escape timers and spawn positions differ "
        "between them **by design**.",
        "",
        "Read these images for: silhouette, relative size, world placement, "
        "layer order, visible armour and regalia state, and colour.",
        "",
        "Do **not** read them for: matching gold, identical enemy counts, the "
        "same wind, or the same timer values. A difference in any of those is "
        "the capture, not the port.",
        "",
        "| scenario | pair image | Java state | what the scene is |",
        "|---|---|---|---|",
    ]
    for name, note in SCENES:
        pair = "compare-%s.png" % name
        exists = os.path.exists(os.path.join(out, pair))
        lines.append("| `%s` | `%s`%s | frame 20, PLAYING | %s |"
                     % (name, pair, "" if exists else " *(missing)*", note))

    lines += [
        "",
        "## Files",
        "",
        "```",
        "compare-<scene>.png    Python above, Java below, captioned",
        "py-<scene>.png         the Python reference alone",
        "<scene>.png            the Java capture alone",
        "contact-sheet.png      all twelve pairs as thumbnails",
        "```",
        "",
        "## What was not compared",
        "",
        "Pixel equality. Pygame and libGDX differ in font rasterisation, "
        "anti-aliasing and primitive filling. No gameplay geometry was changed "
        "to make the two agree, and none should be.",
        "",
    ]
    path = os.path.join(out, "MANIFEST.md")
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines))
    print("manifest: %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
